//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlyrapchieuphim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChoNgoi__SuatChieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChoNgoi__SuatChieu()
        {
            this.Ve1 = new HashSet<Ve1>();
        }
    
        public int ChoNgoi_SuatChieu { get; set; }
        public string trangthai { get; set; }
        public Nullable<int> IDSuatChieu { get; set; }
        public Nullable<int> IDChoNgoi { get; set; }
    
        public virtual ChoNgoi ChoNgoi { get; set; }
        public virtual SuatChieu SuatChieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ve1> Ve1 { get; set; }
    }
}
